# Generated by Django 5.0 on 2023-12-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='receipe',
            new_name='Receipes',
        ),
    ]
